### PR TITLE
Replace webpack with rollup

### PR DESCRIPTION
**Pull request by TrySound**
- rollup does not include 1kb runtime
- rollup generates more compact code
- rollup is able to output es modules
- rollup is easier to configure

Before

33542 prismic-richtext.js
12988 prismic-richtext.min.js

After
22581 prismic-richtext.esm.js
24374 prismic-richtext.js
10259 prismic-richtext.min.js

I also added "module" field for bundlers. "main" refers to not minified
code to simplify debugging.

### CODE REVIEW

**Comment by TrySound** [comment]
cc @hypervillain

**Comment by TrySound** [comment]
Rollup does not support node < 10. Can I drop it from travis?

**Comment by lihbr** [comment]
Hey @TrySound, thank you so much for suggesting those kind of improvements and even working on PRs for them (same goes for prismic-reactjs too!), I'll let the product team know about it!

Sidenote: although being perfectly fine to drop Node 8 & 9 (which are EOL anyway) this will require a major version bump to comply with SemVer.

**Comment by TrySound** [comment]
The project is not node specific and we transpile the code to es5. It should work anyway.

**Comment by lihbr** [comment]
Oh you're right, it's just on the bundle part of it mb, feel free to suggest sure, the team will have a loot at it next week hopefully ☺️

**Comment by TrySound** [comment]
Friendly ping @lihbr

**Comment by lihbr** [comment]
Hey @TrySound thank you for your involvement really appreciate it ☺️

Last week I talked with our PM about it and this will be taken care of soon although I can't give a precise ETA, I'm too looking forward to having all our JavaScript SDKs using rollup~

**Comment by TrySound** [comment]
Great! I will prepare pull requests for other prismic packages I use.

**Comment by lihbr** [comment]
That would be awesome 🚀

**Comment by TrySound** [comment]
Enabled loose mode which gives the following results
16286 prismic-richtext.esm.js
17685 prismic-richtext.js
7522 prismic-richtext.min.js

**Comment by hypervillain** [comment]
Well done, thanks a lot

**Pull request merged**
